apiVersion: v1
kind: Secret
metadata:
  name: mysecret
data:
  password: "eW9nZXNocmVkaGF0"
  db_name: "c3R1ZGVudF9kYg=="
  db_host: "ZGF0YWJhc2UtMS5jZHM0NDR5b2l4cDguYXAtc291dGgtMS5yZHMuYW1hem9uYXdzLmNvbQ=="