# --------- MariaDB ---------
apiVersion: v1
kind: Service
metadata: 
  name: mariadb
spec:
  selector: 
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name:mariadb
spec: 
  selector:
    matchLabel:
      app: mariadb
    template:
      metadata:
        labels:
          app: mariadb
      spec:
        containers:
          - name: mariadb
            image: mariadb:latest
            env:  
              - name: MYSQL_ROOT_PASSWORD
                value: "redhat"
              - name: MYSQL_DATABASE
                value: "student_db"
            ports:
              - containerPort: 3306

# --------- Backend ---------
---
apiVersion: v1
kind: Service
metadata:
  app: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector: 
    matchLabel:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yugajoshi/student-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "mariadb"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "student_db"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "redhat"

# --------- config.js for Frontend ---------
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
data:
   config.js: |
    window.APP_CONFIG = {
      API_URL: "http://a6350f1f134be43c5a8427bdee93499d-710552852.ap-south-1.elb.amazonaws.com:8080/api"
    };

# --------- Frontend ---------
---
apiVersion: v1
kind: Service
metadata:
  name: frontend 
spec: 
  selector:
    app: frontend 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
  type: LoadBalancer
  ---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend 
spec:
  selector:
    matchLabel:   
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend  
          image: yugajoshi/student-frontend:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /var/www/localhost/htdocs/config.js
              subPath: config.js
        volumes:
        - name: config-volume
          configMap:
            name: frontend-config    
